console.log('\n\n');
console.log(process.env);
console.log('\n\n');
console.log('.___  __     __      __             __           ._.');
console.log('|   |/  |_  /  \\    /  \\___________|  | __  _____| |');
console.log('|   \\   __\\ \\   \\/\\/   /  _ \\_  __ \\  |/ / /  ___/ |');
console.log('|   ||  |    \\        (  <_> )  | \\/    <  \\___ \\ \\|');
console.log('|___||__|     \\__/\\  / \\____/|__|  |__|_ \\/____  >__');
console.log('                   \\/                   \\/     \\/ \\/');
console.log('\n\n');
